### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Apartkktrain** [MineDeepRock/team_game_system#1]
TypeError: "Argument 2 passed to team_game_system\model\Team::asNew() must be of the type string, object given, called in D:\PMMP\plugins\example_team_death_match-master\src\example_team_death_match\Main.php on line 35" (EXCEPTION) in "plugins/team_game_system-master/src/team_game_system/model/Team" at line 36

**Comment by Apartkktrain** [comment]
Example Pluinと併用して使用した際に発生しました...

**Comment by suinua** [comment]
サンプルのミスですね、少し前のバージョンのサンプルなので…
Team::asNew("Red", new Color(255, 0, 0)),
などを
Team::asNew("Red", TextFormat::RED),
とかに変えると直ると思います。

(外出中なので…すいません…)

**Comment by Apartkktrain** [comment]
ありがとうございます。
さっそく試してみます。

**Comment by Apartkktrain** [comment]
`use pocketmine\utils\TextFormat;
class Main extends PluginBase implements Listener
{
    private $teamDeathMatchGameIds = [];

    public function onEnable() {
        $this->getServer()->getPluginManager()->registerEvents($this, $this);

        $teams = [
            Team::asNew("Red", TextFormat::RED),
            Team::asNew("Blue", TextFormat::BLUE),`
このようにしたのですがまたエラーが出てしまいました....
 TypeError: "Argument 1 passed to team_game_system\service\AdaptMapToTeamsService::execute() must be an instance of team_game_system\model\Map, null given, called in D:\PMMP\plugins\team_game_system-master\src\team_game_system\TeamGameSystem.php on line 66" (EXCEPTION) in "plugins/team_game_system-master/src/team_game_system/service/AdaptMapToTeamsService" at line 13
たびたび申し訳ありません.....

**Comment by suinua** [comment]
マップが無いからですね。
サーバー内で/mapコマンドを使い、マップを作ってください

**Comment by suinua** [comment]
mapコマンドは少しバグがあるかもしれないので、plugin_data/TeamGameSystem/map以下のファイル(json)をテキストエディタなどで編集する必要があるかもしれないです

**Comment by Apartkktrain** [comment]
ありがとうございます。
さっそく試してみようと思います。
